In [1]:
import pandas as pd

In [8]:
pip install xlrd

Collecting xlrd
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
xlrd

In [9]:
df_arcos = pd.read_excel('pandas_numpy/Prueba_TRANSMILENIO/PSO20220223.xls', sheet_name='Arcos Comerciales y T.Recorrido')
print(df_arcos)

      linea           nodo_1             nodo_2  distancia  descripcion  \
0         2    Portal Sur T6   Flores B - 4 ó 6      20688   A52 Flores
1         2    Portal Sur T6   Flores B - 4 ó 6      20688   A52 Flores
2         2    Portal Sur T6   Flores B - 4 ó 6      20688   A52 Flores
3         2    Portal Sur T6   Flores B - 4 ó 6      20688   A52 Flores
4         2    Portal Sur T6   Flores B - 4 ó 6      20688   A52 Flores
...     ...              ...                ...        ...          ...
1791     48  Portal Tunal T4  Toberín A - 4 ó 6      29336  B71 P.NORTE
1792     48  Portal Tunal T4  Toberín A - 4 ó 6      29336  B71 P.NORTE
1793     48  Portal Tunal T4  Toberín A - 4 ó 6      29336  B71 P.NORTE
1794     48  Portal Tunal T4  Toberín A - 4 ó 6      29336  B71 P.NORTE
1795     48  Portal Tunal T4  Toberín A - 4 ó 6      29336  B71 P.NORTE

     tipodia hora_desde hora_hasta tr_optimo tr_minimo tr_maximo  trayecto  \
0      Habil   01:00:00   05:30:00  00:54:45  00:51:45  00:56:45      1453
1      Habil   05:30:00   06:30:00  01:00:30  00:56:45  01:03:30      1453
2      Habil   06:30:00   08:00:00  01:00:45  00:56:15  01:03:30      1453
3      Habil   08:00:00   09:00:00  00:55:15  00:52:00  00:56:45      1453
4      Habil   09:00:00   16:00:00  00:57:45  00:51:45  01:03:30      1453
...      ...        ...        ...       ...       ...       ...       ...
1791   Habil   16:00:00   17:00:00  01:23:15  01:13:45  01:32:15      1502
1792   Habil   17:00:00   18:30:00  01:23:15  01:13:45  01:32:15      1502
1793   Habil   18:30:00   19:30:00  01:23:15  01:13:45  01:32:15      1502
1794   Habil   19:30:00   20:30:00  01:23:15  01:13:45  01:32:15      1502
1795   Habil   20:30:00   30:00:00  01:23:15  01:13:45  01:32:15      1502

      sentido  secuencia  tipo_arco
0           1          1          1
1           1          1          1
2           1          1          1
3           1          1          1
4           1          1          1
...       ...        ...        ...
1791        1          1          1
1792        1          1          1
1793        1          1          1
1794        1          1          1
1795        1          1          1

[1796 rows x 15 columns]

In [11]:
df_arcos.values

array([[2, 'Portal Sur T6', 'Flores B - 4 ó 6', ..., 1, 1, 1],
       [2, 'Portal Sur T6', 'Flores B - 4 ó 6', ..., 1, 1, 1],
       [2, 'Portal Sur T6', 'Flores B - 4 ó 6', ..., 1, 1, 1],
       ...,
       [48, 'Portal Tunal T4', 'Toberín A - 4 ó 6', ..., 1, 1, 1],
       [48, 'Portal Tunal T4', 'Toberín A - 4 ó 6', ..., 1, 1, 1],
       [48, 'Portal Tunal T4', 'Toberín A - 4 ó 6', ..., 1, 1, 1]],
      dtype=object)

In [12]:
df_arcos.values.head(10)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [13]:
df_arcos.columns

Index(['linea', 'nodo_1', 'nodo_2', 'distancia', 'descripcion', 'tipodia',
       'hora_desde', 'hora_hasta', 'tr_optimo', 'tr_minimo', 'tr_maximo',
       'trayecto', 'sentido', 'secuencia', 'tipo_arco'],
      dtype='object')

In [15]:
df_arcos.index

RangeIndex(start=0, stop=1796, step=1)

In [16]:
df_arcos.sort_values('tr_minimo')

,linea,nodo_1,nodo_2,distancia,descripcion,tipodia,hora_desde,hora_hasta,tr_optimo,tr_minimo,tr_maximo,trayecto,sentido,secuencia,tipo_arco
371,112,CAD B - 2 ó 5,Ricaurte B - 2 ó 5,1737,G43 Art - SAN MATEO,Habil,05:30:00,06:30:00,00:03:17,00:03:07,00:03:26,1013,2,2,1
378,112,CAD B - 2 ó 5,Ricaurte B - 2 ó 5,1737,G43 Art - SAN MATEO,Habil,19:30:00,20:30:00,00:03:17,00:03:07,00:03:26,1013,2,2,1
377,112,CAD B - 2 ó 5,Ricaurte B - 2 ó 5,1737,G43 Art - SAN MATEO,Habil,18:30:00,19:30:00,00:03:17,00:03:07,00:03:26,1013,2,2,1
376,112,CAD B - 2 ó 5,Ricaurte B - 2 ó 5,1737,G43 Art - SAN MATEO,Habil,17:00:00,18:30:00,00:03:17,00:03:07,00:03:26,1013,2,2,1
375,112,CAD B - 2 ó 5,Ricaurte B - 2 ó 5,1737,G43 Art - SAN MATEO,Habil,16:00:00,17:00:00,00:03:17,00:03:07,00:03:26,1013,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,43,Portal Sur T5,Terminal A - 3,30617,B11 Terminal,Habil,06:30:00,08:00:00,1:22:29,1:18:34,1:25:57,1456,1,1,1
1137,11,Portal Tunal T2,Portal Norte T5A,27264,B27 P. Norte,Habil,05:30:00,06:30:00,1:22:30,1:18:45,1:24:30,1462,1,1,1
1462,51,Toberín E - 1,Portal Tunal T5,25418,H73 P. Tunal,Habil,17:00:00,18:30:00,1:26:23,1:18:59,1:33:32,1471,1,1,1
1138,11,Portal Tunal T2,Portal Norte T5A,27264,B27 P. Norte,Habil,06:30:00,08:00:00,1:22:30,1:19:00,1:24:30,1462,1,1,1
1152,11,Portal Norte T5A,Portal Tunal T2,25780,H27 P. Tunal,Habil,17:00:00,18:30:00,1:23:15,1:19:45,1:25:30,1462,2,1,1

In [24]:
df_arcos['tr_minimo'] = pd.to_timedelta

In [25]:
df_arcos

,linea,nodo_1,nodo_2,distancia,descripcion,tipodia,hora_desde,hora_hasta,tr_optimo,tr_minimo,tr_maximo,trayecto,sentido,secuencia,tipo_arco
0,2,Portal Sur T6,Flores B - 4 ó 6,20688,A52 Flores,Habil,01:00:00,05:30:00,00:54:45,<function to_timedelta at 0x0000015CD131D5A0>,00:56:45,1453,1,1,1
1,2,Portal Sur T6,Flores B - 4 ó 6,20688,A52 Flores,Habil,05:30:00,06:30:00,01:00:30,<function to_timedelta at 0x0000015CD131D5A0>,01:03:30,1453,1,1,1
2,2,Portal Sur T6,Flores B - 4 ó 6,20688,A52 Flores,Habil,06:30:00,08:00:00,01:00:45,<function to_timedelta at 0x0000015CD131D5A0>,01:03:30,1453,1,1,1
3,2,Portal Sur T6,Flores B - 4 ó 6,20688,A52 Flores,Habil,08:00:00,09:00:00,00:55:15,<function to_timedelta at 0x0000015CD131D5A0>,00:56:45,1453,1,1,1
4,2,Portal Sur T6,Flores B - 4 ó 6,20688,A52 Flores,Habil,09:00:00,16:00:00,00:57:45,<function to_timedelta at 0x0000015CD131D5A0>,01:03:30,1453,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,48,Portal Tunal T4,Toberín A - 4 ó 6,29336,B71 P.NORTE,Habil,16:00:00,17:00:00,01:23:15,<function to_timedelta at 0x0000015CD131D5A0>,01:32:15,1502,1,1,1
1792,48,Portal Tunal T4,Toberín A - 4 ó 6,29336,B71 P.NORTE,Habil,17:00:00,18:30:00,01:23:15,<function to_timedelta at 0x0000015CD131D5A0>,01:32:15,1502,1,1,1
1793,48,Portal Tunal T4,Toberín A - 4 ó 6,29336,B71 P.NORTE,Habil,18:30:00,19:30:00,01:23:15,<function to_timedelta at 0x0000015CD131D5A0>,01:32:15,1502,1,1,1
1794,48,Portal Tunal T4,Toberín A - 4 ó 6,29336,B71 P.NORTE,Habil,19:30:00,20:30:00,01:23:15,<function to_timedelta at 0x0000015CD131D5A0>,01:32:15,1502,1,1,1
1795,48,Portal Tunal T4,Toberín A - 4 ó 6,29336,B71 P.NORTE,Habil,20:30:00,30:00:00,01:23:15,<function to_timedelta at 0x0000015CD131D5A0>,01:32:15,1502,1,1,1

In [26]:
df_arcos['tr_minimo'] = pd.to_timedelta(df_arcos.tr_minimo)

ValueError: Invalid type for timedelta scalar: <class 'function'>