In [1]:
import pandas as pd

In [14]:
df_datos = pd.read_csv('Stats_Min/Traza_ARL_fasecolda.csv', sep=';', header=0)

In [18]:
df_datos.head(10)

,ID,FechaOperacion,ServicioOrigen,ServicioDestino,Identificador,DatosOperacion,DatosRespuesta,MetaDatos
0,380073807,2022-02-21 05:22:19.297,1001,1002,BAAD7DFB-3787-4623-BC45-856C503ECBA9,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
1,380073810,2022-02-21 05:22:20.833,1001,1002,862A0123-C697-482A-9613-9BFF642DD39F,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
2,380073813,2022-02-21 05:22:22.207,1001,1002,459EA6AD-50E1-4BB4-9FF0-8BE8BB1FEBEB,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Razón social...",NaN
3,380073819,2022-02-21 05:22:24.053,1001,1002,E375A467-18F8-4986-AA21-A38F98FD9EE8,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
4,380073825,2022-02-21 05:22:29.183,1001,1002,9D54180C-B402-4E9F-B3FC-C3748A834A76,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
5,380073829,2022-02-21 05:22:30.590,1001,1002,082B6559-D368-4C15-9467-EE1F575A88D6,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Razón social...",NaN
6,380073836,2022-02-21 05:22:33.907,1001,1002,C2DFAF91-6CA2-4B34-BD0E-4E05A1856CD6,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Ya existe un...",NaN
7,380073839,2022-02-21 05:22:35.190,1001,1002,6CA6F697-C4C3-4DD8-A245-93E725EE8EC9,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Razón social...",NaN
8,380073854,2022-02-21 05:22:38.043,1001,1002,0DF52AE6-79BA-4CC5-9089-66111F0655F8,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Ya existe un...",NaN
9,380073872,2022-02-21 05:22:39.447,1001,1002,50E1BF8A-35C6-44C5-9BB0-1EE647926CD6,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Ya existe un...",NaN

In [21]:
df_datos.sort_values('FechaOperacion', ascending = True)

,ID,FechaOperacion,ServicioOrigen,ServicioDestino,Identificador,DatosOperacion,DatosRespuesta,MetaDatos
0,380073807,2022-02-21 05:22:19.297,1001,1002,BAAD7DFB-3787-4623-BC45-856C503ECBA9,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
1,380073810,2022-02-21 05:22:20.833,1001,1002,862A0123-C697-482A-9613-9BFF642DD39F,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
2,380073813,2022-02-21 05:22:22.207,1001,1002,459EA6AD-50E1-4BB4-9FF0-8BE8BB1FEBEB,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""Razón social...",NaN
3,380073819,2022-02-21 05:22:24.053,1001,1002,E375A467-18F8-4986-AA21-A38F98FD9EE8,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
4,380073825,2022-02-21 05:22:29.183,1001,1002,9D54180C-B402-4E9F-B3FC-C3748A834A76,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""El empleador...",NaN
...,...,...,...,...,...,...,...,...
3858575,408808256,2022-03-09 23:59:57.583,12001,12002,5E1D7FC7-C9C2-4C5F-AB0F-4E5B9D8AC43F,"{ ""IdArl"": 49, ""UsuarioCreacion"": ""8600111...","{ ""resultado"": 0, ""mensaje"": ""Error format...",NaN
3858576,408808258,2022-03-09 23:59:57.693,12001,12002,B203704B-75A2-448A-B299-80CBA676DEC8,"{ ""IdArl"": 49, ""UsuarioCreacion"": ""8600111...","{ ""resultado"": 0, ""mensaje"": ""Error format...",NaN
3858577,408808260,2022-03-09 23:59:57.833,12001,12002,2DEE4145-C98E-41EA-9C0E-CCF8E4A46793,"{ ""IdArl"": 49, ""UsuarioCreacion"": ""8600111...","{ ""resultado"": 0, ""mensaje"": ""Error format...",NaN
3858578,408808263,2022-03-09 23:59:58.037,8001,8002,5A29B4CA-1D93-43F7-BD4C-8E67276F5EB8,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""La sede no e...",NaN
3858579,408808269,2022-03-09 23:59:59.287,8001,8002,B4D27D42-9899-4222-8998-C3CC9CF26D68,"{ ""IdArl"": 43, ""UsuarioCreacion"": ""8002261...","{ ""resultado"": 0, ""mensaje"": ""La sede no e...",NaN

In [32]:
df_datos[df_datos['FechaOperacion'] <= '2022-02-21']

Empty DataFrame
Columns: [ID, FechaOperacion, ServicioOrigen, ServicioDestino, Identificador, DatosOperacion, DatosRespuesta, MetaDatos]
Index: []